menu:
  services_hotel:
    name: services hotel
    url_path: /admin/booking/services_hotels
    icon: rocket
    current: ['/admin/booking/services_hotels']
    model: KepplerBooking::ServicesHotel
    environment: all
    position: 3
  keppler_booking:
    name: Booking
    current: ['/']
    url_path: /
    icon: rocket
    model: User
    environment: all
    position: 4
    submenu:
      - services_room:
          name: services room
          url_path: /admin/booking/services_rooms
          icon: layers
          current: ['/admin/booking/services_rooms']
          model: KepplerBooking::ServicesRoom

      #- order:
          #name: orders
          #url_path: /admin/booking/orders
          #icon: layers
          #current: ['/admin/booking/orders']
          #model: KepplerBooking::Order

      - reservation:
          name: reservations
          url_path: /admin/booking/reservations
          icon: layers
          current: ['/admin/booking/reservations']
          model: KepplerBooking::Reservation

     # - image:
      #    name: images
       #   url_path: /admin/booking/images
        # icon: layers
        #  current: ['/admin/booking/images']
        # model: KepplerBooking::Image

      #- prices_room:
       #   name: prices rooms
        #  url_path: /admin/booking/prices_rooms
         # icon: layers
          #current: ['/admin/booking/prices_rooms']
          #model: KepplerBooking::PricesRoom

      - room:
          name: rooms
          url_path: /admin/booking/rooms
          icon: layers
          current: ['/admin/booking/rooms']
          model: KepplerBooking::Room

      # - new:
      #     name: + Add new module
      #     url_path: /url_path
      #     current: ['/current_path']
      #     enviroment: development
      #     model: User
